name: AutoDaka

# Controls when the action will run. 
on:
  workflow_dispatch:
  watch:
    types: [ started ]
  schedule:
    - cron: 45 */10 * * * # Runs every 45th minute past the 0, 10 and 20th hour. Actions schedules run at most every 5 minutes.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Sync with upstream
        if: github.repository != 'Friedrich-M/AutoClock'
        continue-on-error: true
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.2
        with:
          upstream_sync_repo: Friedrich-M/AutoClock
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_pull_args: '-s recursive -Xtheirs'

      # Runs a single command using the runners shell
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.9
           
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt

      - name: 'Working'
        env: 
          account: ${{ secrets.account }}
          password: ${{ secrets.password }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}

        run: |
          sudo cp -p ./chrome/chromedriver /usr/bin/
          chmod -R 777 /usr/bin/chromedriver
          python daka.py
